repository: FaintGhost/BYR-Navi
repository_url: https://github.com/FaintGhost/BYR-Navi

timezone: Europe/Berlin
lang: zh_CN

title: Navi
alias_en: Navi
alias_cn: 导航
description: A Personal Website
keywords: Navi, Navigation
url: https://nav.awyun.top/
established_at: "2020-02-01T21:36+01:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor